# coding: utf-8

"""
    Manticore Search Client

    Сlient for Manticore Search. 

    The version of the OpenAPI document: 5.0.0
    Contact: info@manticoresearch.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from manticoresearch.api.index_api import IndexApi


class TestIndexApi(unittest.TestCase):
    """IndexApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IndexApi()

    def tearDown(self) -> None:
        pass

    def test_bulk(self) -> None:
        """Test case for bulk

        Bulk table operations
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete a document in a table
        """
        pass

    def test_insert(self) -> None:
        """Test case for insert

        Create a new document in a table
        """
        pass

    def test_partial_replace(self) -> None:
        """Test case for partial_replace

        Partially replaces a document in a table
        """
        pass

    def test_replace(self) -> None:
        """Test case for replace

        Replace new document in a table
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update a document in a table
        """
        pass


if __name__ == '__main__':
    unittest.main()
