# coding: utf-8

"""
    Manticore Search Client

    Сlient for Manticore Search. 

    The version of the OpenAPI document: 5.0.0
    Contact: info@manticoresearch.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from manticoresearch.api.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()

    def tearDown(self) -> None:
        pass

    def test_autocomplete(self) -> None:
        """Test case for autocomplete

        Performs an autocomplete search on a table
        """
        pass

    def test_percolate(self) -> None:
        """Test case for percolate

        Perform reverse search on a percolate table
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        Performs a search on a table
        """
        pass


if __name__ == '__main__':
    unittest.main()
