# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class AggTerms(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, field: str=None, size: int=None):
        """AggTerms - a model defined in OpenAPI

        :param field: The field of this AggTerms.
        :param size: The size of this AggTerms.
        """
        self.openapi_types = {
            'field': str,
            'size': int
        }

        self.attribute_map = {
            'field': 'field',
            'size': 'size'
        }

        self._field = field
        self._size = size

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AggTerms':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The aggTerms of this AggTerms.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def field(self):
        """Gets the field of this AggTerms.

        Name of attribute to aggregate by

        :return: The field of this AggTerms.
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this AggTerms.

        Name of attribute to aggregate by

        :param field: The field of this AggTerms.
        :type field: str
        """
        if field is None:
            raise ValueError("Invalid value for `field`, must not be `None`")

        self._field = field

    @property
    def size(self):
        """Gets the size of this AggTerms.

        Maximum number of buckets in the result

        :return: The size of this AggTerms.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this AggTerms.

        Maximum number of buckets in the result

        :param size: The size of this AggTerms.
        :type size: int
        """

        self._size = size
