# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class AggCompositeSource(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, terms: AggCompositeTerm=None):
        """AggCompositeSource - a model defined in OpenAPI

        :param terms: The terms of this AggCompositeSource.
        """
        self.openapi_types = {
            'terms': AggCompositeTerm
        }

        self.attribute_map = {
            'terms': 'terms'
        }

        self._terms = terms

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AggCompositeSource':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The aggCompositeSource of this AggCompositeSource.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def terms(self):
        """Gets the terms of this AggCompositeSource.


        :return: The terms of this AggCompositeSource.
        :rtype: AggCompositeTerm
        """
        return self._terms

    @terms.setter
    def terms(self, terms):
        """Sets the terms of this AggCompositeSource.


        :param terms: The terms of this AggCompositeSource.
        :type terms: AggCompositeTerm
        """
        if terms is None:
            raise ValueError("Invalid value for `terms`, must not be `None`")

        self._terms = terms
