# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class BulkResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items: List[object]=None, errors: bool=None, error: str=None, current_line: int=None, skipped_lines: int=None):
        """BulkResponse - a model defined in OpenAPI

        :param items: The items of this BulkResponse.
        :param errors: The errors of this BulkResponse.
        :param error: The error of this BulkResponse.
        :param current_line: The current_line of this BulkResponse.
        :param skipped_lines: The skipped_lines of this BulkResponse.
        """
        self.openapi_types = {
            'items': List[object],
            'errors': bool,
            'error': str,
            'current_line': int,
            'skipped_lines': int
        }

        self.attribute_map = {
            'items': 'items',
            'errors': 'errors',
            'error': 'error',
            'current_line': 'current_line',
            'skipped_lines': 'skipped_lines'
        }

        self._items = items
        self._errors = errors
        self._error = error
        self._current_line = current_line
        self._skipped_lines = skipped_lines

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BulkResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The bulkResponse of this BulkResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this BulkResponse.

        List of results

        :return: The items of this BulkResponse.
        :rtype: List[object]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this BulkResponse.

        List of results

        :param items: The items of this BulkResponse.
        :type items: List[object]
        """

        self._items = items

    @property
    def errors(self):
        """Gets the errors of this BulkResponse.

        Errors occurred during the bulk operation

        :return: The errors of this BulkResponse.
        :rtype: bool
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this BulkResponse.

        Errors occurred during the bulk operation

        :param errors: The errors of this BulkResponse.
        :type errors: bool
        """

        self._errors = errors

    @property
    def error(self):
        """Gets the error of this BulkResponse.

        Error message describing an error if such occurred

        :return: The error of this BulkResponse.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this BulkResponse.

        Error message describing an error if such occurred

        :param error: The error of this BulkResponse.
        :type error: str
        """

        self._error = error

    @property
    def current_line(self):
        """Gets the current_line of this BulkResponse.

        Number of the row returned in the response

        :return: The current_line of this BulkResponse.
        :rtype: int
        """
        return self._current_line

    @current_line.setter
    def current_line(self, current_line):
        """Sets the current_line of this BulkResponse.

        Number of the row returned in the response

        :param current_line: The current_line of this BulkResponse.
        :type current_line: int
        """

        self._current_line = current_line

    @property
    def skipped_lines(self):
        """Gets the skipped_lines of this BulkResponse.

        Number of rows skipped in the response

        :return: The skipped_lines of this BulkResponse.
        :rtype: int
        """
        return self._skipped_lines

    @skipped_lines.setter
    def skipped_lines(self, skipped_lines):
        """Sets the skipped_lines of this BulkResponse.

        Number of rows skipped in the response

        :param skipped_lines: The skipped_lines of this BulkResponse.
        :type skipped_lines: int
        """

        self._skipped_lines = skipped_lines
