# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class DeleteDocumentRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, table: str=None, cluster: str=None, id: int=None, query: object=None):
        """DeleteDocumentRequest - a model defined in OpenAPI

        :param table: The table of this DeleteDocumentRequest.
        :param cluster: The cluster of this DeleteDocumentRequest.
        :param id: The id of this DeleteDocumentRequest.
        :param query: The query of this DeleteDocumentRequest.
        """
        self.openapi_types = {
            'table': str,
            'cluster': str,
            'id': int,
            'query': object
        }

        self.attribute_map = {
            'table': 'table',
            'cluster': 'cluster',
            'id': 'id',
            'query': 'query'
        }

        self._table = table
        self._cluster = cluster
        self._id = id
        self._query = query

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DeleteDocumentRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The deleteDocumentRequest of this DeleteDocumentRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def table(self):
        """Gets the table of this DeleteDocumentRequest.

        Table name

        :return: The table of this DeleteDocumentRequest.
        :rtype: str
        """
        return self._table

    @table.setter
    def table(self, table):
        """Sets the table of this DeleteDocumentRequest.

        Table name

        :param table: The table of this DeleteDocumentRequest.
        :type table: str
        """
        if table is None:
            raise ValueError("Invalid value for `table`, must not be `None`")

        self._table = table

    @property
    def cluster(self):
        """Gets the cluster of this DeleteDocumentRequest.

        Cluster name

        :return: The cluster of this DeleteDocumentRequest.
        :rtype: str
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster):
        """Sets the cluster of this DeleteDocumentRequest.

        Cluster name

        :param cluster: The cluster of this DeleteDocumentRequest.
        :type cluster: str
        """

        self._cluster = cluster

    @property
    def id(self):
        """Gets the id of this DeleteDocumentRequest.

        The ID of document for deletion

        :return: The id of this DeleteDocumentRequest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DeleteDocumentRequest.

        The ID of document for deletion

        :param id: The id of this DeleteDocumentRequest.
        :type id: int
        """

        self._id = id

    @property
    def query(self):
        """Gets the query of this DeleteDocumentRequest.

        Defines the criteria to match documents for deletion

        :return: The query of this DeleteDocumentRequest.
        :rtype: object
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this DeleteDocumentRequest.

        Defines the criteria to match documents for deletion

        :param query: The query of this DeleteDocumentRequest.
        :type query: object
        """

        self._query = query
