# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class ErrorResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error: ResponseError=None, status: int=500):
        """ErrorResponse - a model defined in OpenAPI

        :param error: The error of this ErrorResponse.
        :param status: The status of this ErrorResponse.
        """
        self.openapi_types = {
            'error': ResponseError,
            'status': int
        }

        self.attribute_map = {
            'error': 'error',
            'status': 'status'
        }

        self._error = error
        self._status = status

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The errorResponse of this ErrorResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self):
        """Gets the error of this ErrorResponse.


        :return: The error of this ErrorResponse.
        :rtype: ResponseError
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this ErrorResponse.


        :param error: The error of this ErrorResponse.
        :type error: ResponseError
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")

        self._error = error

    @property
    def status(self):
        """Gets the status of this ErrorResponse.

        HTTP status code of the error response

        :return: The status of this ErrorResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ErrorResponse.

        HTTP status code of the error response

        :param status: The status of this ErrorResponse.
        :type status: int
        """

        self._status = status
