# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class GeoDistanceLocationAnchor(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, lat: object=None, lon: object=None):
        """GeoDistanceLocationAnchor - a model defined in OpenAPI

        :param lat: The lat of this GeoDistanceLocationAnchor.
        :param lon: The lon of this GeoDistanceLocationAnchor.
        """
        self.openapi_types = {
            'lat': object,
            'lon': object
        }

        self.attribute_map = {
            'lat': 'lat',
            'lon': 'lon'
        }

        self._lat = lat
        self._lon = lon

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GeoDistanceLocationAnchor':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The geoDistance_location_anchor of this GeoDistanceLocationAnchor.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self):
        """Gets the lat of this GeoDistanceLocationAnchor.

        Latitude of the anchor point

        :return: The lat of this GeoDistanceLocationAnchor.
        :rtype: object
        """
        return self._lat

    @lat.setter
    def lat(self, lat):
        """Sets the lat of this GeoDistanceLocationAnchor.

        Latitude of the anchor point

        :param lat: The lat of this GeoDistanceLocationAnchor.
        :type lat: object
        """

        self._lat = lat

    @property
    def lon(self):
        """Gets the lon of this GeoDistanceLocationAnchor.

        Longitude of the anchor point

        :return: The lon of this GeoDistanceLocationAnchor.
        :rtype: object
        """
        return self._lon

    @lon.setter
    def lon(self, lon):
        """Sets the lon of this GeoDistanceLocationAnchor.

        Longitude of the anchor point

        :param lon: The lon of this GeoDistanceLocationAnchor.
        :type lon: object
        """

        self._lon = lon
