# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class InsertDocumentRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, table: str=None, cluster: str=None, id: int=None, doc: object=None):
        """InsertDocumentRequest - a model defined in OpenAPI

        :param table: The table of this InsertDocumentRequest.
        :param cluster: The cluster of this InsertDocumentRequest.
        :param id: The id of this InsertDocumentRequest.
        :param doc: The doc of this InsertDocumentRequest.
        """
        self.openapi_types = {
            'table': str,
            'cluster': str,
            'id': int,
            'doc': object
        }

        self.attribute_map = {
            'table': 'table',
            'cluster': 'cluster',
            'id': 'id',
            'doc': 'doc'
        }

        self._table = table
        self._cluster = cluster
        self._id = id
        self._doc = doc

    @classmethod
    def from_dict(cls, dikt: dict) -> 'InsertDocumentRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The insertDocumentRequest of this InsertDocumentRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def table(self):
        """Gets the table of this InsertDocumentRequest.

        Name of the table to insert the document into

        :return: The table of this InsertDocumentRequest.
        :rtype: str
        """
        return self._table

    @table.setter
    def table(self, table):
        """Sets the table of this InsertDocumentRequest.

        Name of the table to insert the document into

        :param table: The table of this InsertDocumentRequest.
        :type table: str
        """
        if table is None:
            raise ValueError("Invalid value for `table`, must not be `None`")

        self._table = table

    @property
    def cluster(self):
        """Gets the cluster of this InsertDocumentRequest.

        Name of the cluster to insert the document into

        :return: The cluster of this InsertDocumentRequest.
        :rtype: str
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster):
        """Sets the cluster of this InsertDocumentRequest.

        Name of the cluster to insert the document into

        :param cluster: The cluster of this InsertDocumentRequest.
        :type cluster: str
        """

        self._cluster = cluster

    @property
    def id(self):
        """Gets the id of this InsertDocumentRequest.

        Document ID. If not provided, an ID will be auto-generated 

        :return: The id of this InsertDocumentRequest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InsertDocumentRequest.

        Document ID. If not provided, an ID will be auto-generated 

        :param id: The id of this InsertDocumentRequest.
        :type id: int
        """

        self._id = id

    @property
    def doc(self):
        """Gets the doc of this InsertDocumentRequest.

        Object containing document data 

        :return: The doc of this InsertDocumentRequest.
        :rtype: object
        """
        return self._doc

    @doc.setter
    def doc(self, doc):
        """Sets the doc of this InsertDocumentRequest.

        Object containing document data 

        :param doc: The doc of this InsertDocumentRequest.
        :type doc: object
        """
        if doc is None:
            raise ValueError("Invalid value for `doc`, must not be `None`")

        self._doc = doc
