# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class PercolateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, query: PercolateRequestQuery=None):
        """PercolateRequest - a model defined in OpenAPI

        :param query: The query of this PercolateRequest.
        """
        self.openapi_types = {
            'query': PercolateRequestQuery
        }

        self.attribute_map = {
            'query': 'query'
        }

        self._query = query

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PercolateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The percolateRequest of this PercolateRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def query(self):
        """Gets the query of this PercolateRequest.


        :return: The query of this PercolateRequest.
        :rtype: PercolateRequestQuery
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this PercolateRequest.


        :param query: The query of this PercolateRequest.
        :type query: PercolateRequestQuery
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")

        self._query = query
