# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class Range(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, lt: object=None, lte: object=None, gt: object=None, gte: object=None):
        """Range - a model defined in OpenAPI

        :param lt: The lt of this Range.
        :param lte: The lte of this Range.
        :param gt: The gt of this Range.
        :param gte: The gte of this Range.
        """
        self.openapi_types = {
            'lt': object,
            'lte': object,
            'gt': object,
            'gte': object
        }

        self.attribute_map = {
            'lt': 'lt',
            'lte': 'lte',
            'gt': 'gt',
            'gte': 'gte'
        }

        self._lt = lt
        self._lte = lte
        self._gt = gt
        self._gte = gte

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Range':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The range of this Range.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lt(self):
        """Gets the lt of this Range.


        :return: The lt of this Range.
        :rtype: object
        """
        return self._lt

    @lt.setter
    def lt(self, lt):
        """Sets the lt of this Range.


        :param lt: The lt of this Range.
        :type lt: object
        """

        self._lt = lt

    @property
    def lte(self):
        """Gets the lte of this Range.


        :return: The lte of this Range.
        :rtype: object
        """
        return self._lte

    @lte.setter
    def lte(self, lte):
        """Sets the lte of this Range.


        :param lte: The lte of this Range.
        :type lte: object
        """

        self._lte = lte

    @property
    def gt(self):
        """Gets the gt of this Range.


        :return: The gt of this Range.
        :rtype: object
        """
        return self._gt

    @gt.setter
    def gt(self, gt):
        """Sets the gt of this Range.


        :param gt: The gt of this Range.
        :type gt: object
        """

        self._gt = gt

    @property
    def gte(self):
        """Gets the gte of this Range.


        :return: The gte of this Range.
        :rtype: object
        """
        return self._gte

    @gte.setter
    def gte(self, gte):
        """Sets the gte of this Range.


        :param gte: The gte of this Range.
        :type gte: object
        """

        self._gte = gte
