# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class ResponseErrorDetails(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, reason: str=None, table: str=None):
        """ResponseErrorDetails - a model defined in OpenAPI

        :param type: The type of this ResponseErrorDetails.
        :param reason: The reason of this ResponseErrorDetails.
        :param table: The table of this ResponseErrorDetails.
        """
        self.openapi_types = {
            'type': str,
            'reason': str,
            'table': str
        }

        self.attribute_map = {
            'type': 'type',
            'reason': 'reason',
            'table': 'table'
        }

        self._type = type
        self._reason = reason
        self._table = table

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ResponseErrorDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The responseErrorDetails of this ResponseErrorDetails.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this ResponseErrorDetails.

        Type or category of the error

        :return: The type of this ResponseErrorDetails.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ResponseErrorDetails.

        Type or category of the error

        :param type: The type of this ResponseErrorDetails.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def reason(self):
        """Gets the reason of this ResponseErrorDetails.

        Detailed explanation of why the error occurred

        :return: The reason of this ResponseErrorDetails.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ResponseErrorDetails.

        Detailed explanation of why the error occurred

        :param reason: The reason of this ResponseErrorDetails.
        :type reason: str
        """

        self._reason = reason

    @property
    def table(self):
        """Gets the table of this ResponseErrorDetails.

        The table related to the error, if applicable

        :return: The table of this ResponseErrorDetails.
        :rtype: str
        """
        return self._table

    @table.setter
    def table(self, table):
        """Sets the table of this ResponseErrorDetails.

        The table related to the error, if applicable

        :param table: The table of this ResponseErrorDetails.
        :type table: str
        """

        self._table = table
