# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class SourceRules(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, includes: object=None, excludes: object=None):
        """SourceRules - a model defined in OpenAPI

        :param includes: The includes of this SourceRules.
        :param excludes: The excludes of this SourceRules.
        """
        self.openapi_types = {
            'includes': object,
            'excludes': object
        }

        self.attribute_map = {
            'includes': 'includes',
            'excludes': 'excludes'
        }

        self._includes = includes
        self._excludes = excludes

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SourceRules':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The sourceRules of this SourceRules.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def includes(self):
        """Gets the includes of this SourceRules.

        List of fields to include in the response

        :return: The includes of this SourceRules.
        :rtype: object
        """
        return self._includes

    @includes.setter
    def includes(self, includes):
        """Sets the includes of this SourceRules.

        List of fields to include in the response

        :param includes: The includes of this SourceRules.
        :type includes: object
        """

        self._includes = includes

    @property
    def excludes(self):
        """Gets the excludes of this SourceRules.

        List of fields to exclude from the response

        :return: The excludes of this SourceRules.
        :rtype: object
        """
        return self._excludes

    @excludes.setter
    def excludes(self, excludes):
        """Sets the excludes of this SourceRules.

        List of fields to exclude from the response

        :param excludes: The excludes of this SourceRules.
        :type excludes: object
        """

        self._excludes = excludes
