# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from manticoresearch.models.base_model import Model
from manticoresearch import util


class UpdateResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, table: str=None, updated: int=None, id: int=None, result: str=None):
        """UpdateResponse - a model defined in OpenAPI

        :param table: The table of this UpdateResponse.
        :param updated: The updated of this UpdateResponse.
        :param id: The id of this UpdateResponse.
        :param result: The result of this UpdateResponse.
        """
        self.openapi_types = {
            'table': str,
            'updated': int,
            'id': int,
            'result': str
        }

        self.attribute_map = {
            'table': 'table',
            'updated': 'updated',
            'id': 'id',
            'result': 'result'
        }

        self._table = table
        self._updated = updated
        self._id = id
        self._result = result

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UpdateResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The updateResponse of this UpdateResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def table(self):
        """Gets the table of this UpdateResponse.

        Name of the document table

        :return: The table of this UpdateResponse.
        :rtype: str
        """
        return self._table

    @table.setter
    def table(self, table):
        """Sets the table of this UpdateResponse.

        Name of the document table

        :param table: The table of this UpdateResponse.
        :type table: str
        """

        self._table = table

    @property
    def updated(self):
        """Gets the updated of this UpdateResponse.

        Number of documents updated

        :return: The updated of this UpdateResponse.
        :rtype: int
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this UpdateResponse.

        Number of documents updated

        :param updated: The updated of this UpdateResponse.
        :type updated: int
        """

        self._updated = updated

    @property
    def id(self):
        """Gets the id of this UpdateResponse.

        Document ID

        :return: The id of this UpdateResponse.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UpdateResponse.

        Document ID

        :param id: The id of this UpdateResponse.
        :type id: int
        """

        self._id = id

    @property
    def result(self):
        """Gets the result of this UpdateResponse.

        Result of the update operation, typically 'updated'

        :return: The result of this UpdateResponse.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this UpdateResponse.

        Result of the update operation, typically 'updated'

        :param result: The result of this UpdateResponse.
        :type result: str
        """

        self._result = result
